# https://github.com/changesets/action
name: Release Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  pull-requests: write
  contents: write

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Add Rust WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-pack
        run: cargo install wasm-pack --locked && wasm-pack --version
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          run_install: true

      # consume changesets and create pr if it exists, otherwise publish package
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: pnpm exec changeset publish
          commit: 'chore: versioning package'
          title: 'chore:versioning package'
